sudo: false
dist: xenial
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - pip3 install codecov --upgrade

script:
  - coverage run tests/test_basic.py

after_success:
  - codecov
